### ISSUE TITLE
Using plugins section empty

### ISSUE THREAD

**Issue by hackerunet** [angel-dart/gitbook#2]
The section of using plugins is empty and it was updated 5 months ago.
So if previous observations point this section as key to develop a MVC application why is it empty? It generate doubts about this framework.

**Comment by thosakwe** [comment]
1. The page is **not empty** - the content is in this very repo: https://github.com/angel-dart/gitbook/blob/master/the-basics/using-plug-ins.md. It seems to be an upstream issue with Gitbook. When I have time, I'll send them an e-mail.
2. Angel has been undergoing a *large* upgrade for the past few months, and the actual code is a higher priority than upgrading documentation for a now-outdated version.
3. If you think this is mission-critical, feel free to send in a PR with the necessary content.
